#!/bin/zsh

FILE='./data/~$test_wb.xlsm'
if [[ -f "$FILE" ]]; then
    echo "$FILE exists indicating target is open."
    exit 1
fi

#
# pull latest vba from fcast.xlms and build the test spreadsheet and open it
dance/util/vba/extract_vba.py    
dance/util/vba/sort_vba.py

# document the lambdas
dance/util/doc_lambda.py

target="data/test_wb.xlsm"

# run the main build
dance/setup/create_wb.py $target -o
RC=$?
if [ $RC -ne 0 ]; then
  echo "create_wb failed"
  exit $RC
fi

# load preserved values
dance/preserve_changed.py -l

# pull in the ytd reprojections
dance/ytd.py -l -f

# use script to open and save
# this allows Excel to compute the formulas and setup some hidden defined names
osascript ./dance/util/excel_save.scpt

# Calc props after excel sets the calcId
dance/setup/calc_props.py -w $target
