#!/bin/zsh
#
# pull latest vba from fcast.xlms and build the test spreadsheet and open it
dance/util/vba/extract_vba.py    
dance/util/vba/sort_vba.py 
dance/setup/create_wb.py data/test_wb.xlsm -o
open data/test_wb.xlsm  
