#!/bin/zsh

# items to reduce to 40% and put a border around
for f in data_validation.png time_series.png calc_option.png
do
  echo "Processing $f"
  magick "src/$f" -resize 40% -bordercolor navyblue -border 1 -alpha set -bordercolor none -border 50x0 "tgt/$f"
done
