#!/bin/zsh

# items to reduce to 40% and put a border around are in src/std
for f in src/std/*
do
  echo "Processing $f:t"

  magick "$f" -resize 40% -bordercolor navyblue -border 1 -alpha set -bordercolor none -border 50x0 "tgt/$f:t"
done
